/**
 * PRECEDENCE protocol types — single source of truth for all shared types.
 *
 * The Proof-Ordered Capital Priority Protocol:
 *  - Ethereum Sepolia (chainKey 1) = source-chain capital locks (PriorityVault.sol, pUSD)
 *  - Creditcoin CC3 = Attestcoin Native Query Verifier precompile (0x0FD2), AttestationGate,
 *    PriorityEngine, CollateralRegistry, ClaimToken (ERC-1155), RefinanceEngine.
 *
 * Priority settles by proven `(blockHeight, txIndex)` ordering, where txIndex is derived on-chain
 * from the Merkle proof via `INativeQueryVerifier.calculateTxIndex`. A declared tranche is a
 * *preference*; proven ordering resolves contention within it.
 */

export type Hex = `0x${string}`;
export type AgentId = string; // "meridian" | "vector" | "novum" | "kestrel"
export type RaceId = string;
export type CollateralId = string;
export type ISO = string; // ISO-8601 timestamp

export type Tranche = "SENIOR" | "JUNIOR" | "SUBORDINATE";
export type TrancheNumber = 0 | 1 | 2; // 0=SENIOR, 1=JUNIOR, 2=SUBORDINATE

export type CollateralState =
  | "CLEAR"
  | "RACE_OPEN"
  | "PRIORITY_SETTLED"
  | "ENCUMBERED"
  | "FROZEN"
  | "GRACE"
  | "DUTCH_LIQUIDATION"
  | "REPAID"
  | "REFINANCED"
  | "DEFAULTED"
  | "BREACHED";

export type ProofPipelineStatus =
  | "PENDING_EVIDENCE" // source tx exists; attestation has not reached its height yet (a patient state)
  | "PROOF_AVAILABLE" // proof generated by the builder service
  | "VERIFIED" // precompile 0x0FD2 returned true on Creditcoin
  | "FAILED";

export type RiskTolerance = "conservative" | "balanced" | "aggressive";

// ───────────────────────────── Financier Agents ─────────────────────────────

export interface FinancierPolicy {
  /** Hard cap on capital this financier will commit to one collateral race (USD). */
  maxCapitalUsd: number;
  /** Minimum required interest rate (percent). */
  minRatePct: number;
  riskTolerance: RiskTolerance;
  /** Maximum acceptable collateral risk score (0..1). */
  maxRiskScore: number;
  /** Target tranche rank preference — a preference, not an entitlement. */
  preferredTranche: Tranche;
  /** Require strictly clear title (zero prior liens recorded on Creditcoin). */
  requiredClearTitle: boolean;
  /** Maximum loan-to-value percentage. */
  maxLtvPct: number;
  /** May counter with a smaller capital commitment. */
  allowJoinSmaller: boolean;
  /**
   * Opt in to being demoted to a lower tranche if outpaced in the declared one.
   * Default false: a SENIOR bidder never implicitly consents to subordinate risk.
   */
  allowDemotion: boolean;
}

export interface ClaimIdentity {
  tokenId: string;
  registryAddress: Hex | "";
  ownerAddress: Hex | "";
}

export interface FinancierWallet {
  publicKey: string;
  address: Hex;
  label: string;
}

export interface ReputationSummary {
  count: number;
  avgScore: number;
  verifiedProofs: number;
  lastTxHash?: Hex;
}

export interface FinancierStats {
  racesJoined: number;
  racesWon: number;
  racesInitiated: number;
  volumeSettledUsd: number;
  claimsActive: number;
  defaultLossUsd: number;
  totalEarnedUsd: number;
  winRatePct: number;
  lastAction?: string;
  lastActionAt?: ISO;
}

export interface Agent {
  id: AgentId;
  name: string;
  role: "senior_financier" | "junior_financier" | "subordinate_financier" | "prover";
  mandate: string;
  persona: string;
  identity: ClaimIdentity;
  wallet: FinancierWallet;
  policy: FinancierPolicy;
  balanceUsd: number;
  reputation: ReputationSummary;
  stats: FinancierStats;
  createdAt: ISO;
}

// ───────────────────────────── Collateral Assets ─────────────────────────────

export type CollateralAssetType = "warehouse-receipt" | "trade-receivable" | "commodity-pledge";

/**
 * Facility terms, posted by the BORROWER when opening a facility.
 *
 * @remarks The borrower fixes the coupon per tranche; lenders accept those terms or do not bid.
 * That is what keeps proven ordering load-bearing — lenders compete on WHEN their lock landed, not
 * on price, so `(blockHeight, txIndex)` decides who gets an oversubscribed tranche and therefore
 * decides real money. If lenders bid rates, price would decide allocation and the ordering proof
 * would degrade into a tiebreak for the rare case of equal bids.
 *
 * Rates must be ordinal — senior <= junior <= subordinate — because senior is protected by
 * everything beneath it and so must be the cheapest capital. The contract enforces it.
 */
export interface FacilityTerms {
  seniorCapUsd: number;
  juniorCapUsd: number;
  subordinateCapUsd: number;
  seniorRatePct: number;
  juniorRatePct: number;
  subordinateRatePct: number;
  termDays: number;
  postedAt?: ISO;
}

/**
 * Fields a model believes it read from an unregistered document.
 *
 * @remarks Distinct from `DocumentExtraction`, which is *ratified against* an existing on-chain
 * record. At registration time there is no record yet — the document is all there is — so nothing
 * can be corroborated and none of this is evidence. It exists solely to pre-fill a form the
 * borrower must then read and confirm, and every field stays independently editable. The borrower
 * signing the transaction is what makes any of it a claim.
 */
export interface RegistrationProposal {
  assetType?: CollateralAssetType;
  title?: string;
  /** The receipt or invoice reference as printed. */
  docIdentifier?: string;
  obligor?: string;
  custodian?: string;
  custodianLocation?: string;
  faceValueUsd?: number;
  termDays?: number;
  /** The model's own 0-1 confidence. Displayed, never acted on. */
  confidence: number;
  /** Anything the reader should be suspicious of — missing dates, hedged language, alterations. */
  concerns: string[];
  model: string;
  extractedAt: ISO;
}

export interface CollateralAsset {
  id: string;
  assetType: CollateralAssetType;
  title: string;
  symbol: string;
  obligor: string;
  /**
   * The obligor's wallet. This is what a connected wallet is matched against to derive whether
   * someone is a borrower here — `obligor` above is a display name and cannot identify anyone.
   */
  obligorAddress: Hex;
  custodian: string;
  custodianLocation: string;
  faceValueUsd: number;
  financingRequestedUsd: number;
  haircutPct: number; // e.g. 15%
  advanceRatePct: number; // e.g. 85%
  termDays: number;
  currentRatePct: number;
  targetRatePct: number;
  docHash: Hex;
  nftTokenId: string;
  registryAddress: Hex;
  /** The Sepolia PriorityVault every proof for this collateral MUST be bound to. */
  vaultAddress: Hex;
  /** Posted by the obligor. Absent until they open a facility. */
  terms?: FacilityTerms;
  status: CollateralState;
  riskLabel: "Low" | "Medium" | "High";
  riskScore: number;
  verifiedClearTitle: boolean;
  fetchedAt: ISO;
  source: "creditcoin-registry" | "mock";
  /**
   * Receipts from the obligor's own on-chain registration, when they signed one.
   *
   * @remarks Kept on the asset rather than shown once and forgotten. The registration wizard
   * displayed these on its success screen and then dropped them, so the two Creditcoin
   * transactions a borrower had just signed and watched confirm in their wallet existed nowhere in
   * the app a moment later — the facility page they landed on could not link to either. A receipt
   * that only exists until the next navigation is not evidence.
   *
   * Absent on a simulated registration, which is what keeps this from ever being a fabricated
   * link: no signature, no hashes, no card.
   */
  onChainRefs?: {
    /** CollateralRegistry.registerCollateral on Creditcoin CC3. */
    creditcoinRegisterTx?: Hex;
    /** CollateralRegistry.postFacilityTerms on Creditcoin CC3. */
    creditcoinTermsTx?: Hex;
  };
}

export interface CollateralAnalysis {
  collateralId: string;
  estRatePct: number;
  riskScore: number;
  advanceRatePct: number;
  haircutUsd: number;
  maxDrawUsd: number;
  notes: string[];
  /**
   * A SUGGESTION for the borrower's form, not the facility.
   * @remarks Once the borrower posts terms, `CollateralAsset.terms` is authoritative and this is
   * only a starting point for the pre-fill. Confusing the two would let the UI show a rate the
   * lender is not actually being offered.
   */
  suggestedTranches: {
    seniorUsd: number;
    juniorUsd: number;
    subordinateUsd: number;
    seniorRatePct: number;
    juniorRatePct: number;
    subordinateRatePct: number;
  };
}

/**
 * Fields an LLM extracted from an unstructured collateral document.
 *
 * This is a PROPOSAL, never evidence. `domain/policy.ts` ratifies it against hard limits before
 * any capital decision is made, and nothing here is ever treated as proven.
 */
export interface DocumentExtraction {
  collateralId: string;
  faceValueUsd?: number;
  obligor?: string;
  custodian?: string;
  expiry?: ISO;
  assetDescription?: string;
  confidence: number; // 0..1, self-reported by the model
  source: "llm" | "manual";
  model?: string;
  ratified: boolean; // set true only after the deterministic policy filter accepts it
  ratificationNotes: string[];
  extractedAt: ISO;
}

export interface RefinanceOpportunity {
  collateralId: string;
  obligor: string;
  currentSeniorRatePct: number;
  proposedSeniorRatePct: number;
  spreadSavingsBps: number;
  annualSavingsUsd: number;
  notionalUsd: number;
  candidateFinancier: AgentId;
}

// ───────────────────────────── Decisions & Bids ─────────────────────────────

export type DecisionVerb = "bid-senior" | "bid-junior" | "bid-subordinate" | "decline" | "join-smaller";

export interface AgentDecision {
  agentId: AgentId;
  verb: DecisionVerb;
  tranche: Tranche;
  amountUsd: number;
  ratePct: number;
  expectedUtility: number;
  reasoning: string;
  /** `policy` = deterministic and authoritative. `agent_runtime` = LLM narration only. */
  source: "policy" | "agent_runtime";
  decidedAt: ISO;
}

/**
 * A competing financier's bid into a priority race.
 *
 * These are rival lenders, not a syndicate: there is no initiator and nothing is pooled.
 * Allocation is decided by proven source-chain ordering, not by agreement.
 */
export interface FinancierBid {
  agentId: AgentId;
  tranche: Tranche;
  requestedUsd: number;
  committedUsd: number;
  allowDemotion: boolean;
  lockBlockNumber?: number;
  lockTxIndex?: number;
  lockSeq?: number;
  sepoliaTxHash?: Hex;
}

// ───────────────────────────── Source Lock & Proof ─────────────────────────────

export interface SourceLockRecord {
  collateralId: string;
  financier: AgentId;
  financierAddress: Hex;
  tranche: Tranche;
  amountUsd: number;
  /** Canonical source-chain block height — half of the priority root. */
  lockBlockNumber: number;
  /** Canonical intra-block position, derived on-chain via calculateTxIndex — the other half. */
  lockTxIndex: number;
  /** PriorityVault's per-collateral monotonic counter. Proves the submitted set is COMPLETE. */
  seq: number;
  /** Settlement token address, carried in the Lock event so CC3 never infers denomination. */
  token: Hex;
  sepoliaTxHash: Hex;
  /** The precompile does NOT check this — the dApp must, and does. */
  receiptStatus: 1;
  /** The vault that emitted the Lock event. Must equal collateral.vaultAddress. */
  emittedBy: Hex;
  timestamp: ISO;
  refunded: boolean;
}

/** Mirrors INativeQueryVerifier.MerkleProof. */
export interface MerkleProofData {
  root: Hex;
  siblings: { hash: Hex; isLeft: boolean }[];
}

/** Mirrors INativeQueryVerifier.ContinuityProof. */
export interface ContinuityProofData {
  lowerEndpointDigest: Hex;
  roots: Hex[];
}

/**
 * One Attestcoin verification of a priority race.
 *
 * Shaped to the real batch overload:
 *   verifyAndEmit(uint64 chainKey, uint64[] heights, bytes[] encodedTxs,
 *                 MerkleProof[] merkleProofs, ContinuityProof sharedContinuityProof)
 * A single continuity proof is shared across up to 10 transactions within a 1000-block window.
 */
export interface AttestcoinProofRecord {
  chainKey: number; // 1 = Sepolia
  /** One height per transaction — a race legitimately spans blocks. */
  heights: number[];
  /** Derived from each Merkle proof by calculateTxIndex, aligned with `heights`. */
  txIndices: number[];
  encodedTxs: Hex[];
  merkleProofs: MerkleProofData[];
  continuityProof: ContinuityProofData;
  batchSize: number;
  /** True once the free view-only `verify` passed off-chain, before spending gas. */
  preflightVerified: boolean;
  proofPipelineStatus: ProofPipelineStatus;
  /** Measured, not assumed: 6.5-9.3 min sawtooth on Sepolia, n=239 as of 2026-09-02. */
  attestationLagMinutes: number;
  /** Latest attested height reported by ChainInfo precompile 0x0FD3 when the proof was built. */
  attestedHeight?: number;
  proverAgent: AgentId;
  precompile: Hex;
  creditcoinTxHash?: Hex;
  verificationBlockNumber?: number;
  verifiedAt?: ISO;
  error?: string;
}

export interface PriorityClaim {
  claimId: string;
  collateralId: string;
  tranche: Tranche;
  holder: AgentId;
  holderAddress: Hex;
  principalUsd: number;
  ratePct: number;
  tokenId: string; // ERC-1155 position
  priorityRank: 1 | 2 | 3;
  /** The proven ordering that won this rank. */
  provenAt: { blockNumber: number; txIndex: number; seq: number };
  state: "ACTIVE" | "REPAID" | "REFINANCED" | "DEFAULTED" | "LIQUIDATED";
  mintedAt: ISO;
}

export interface RefundRecord {
  agentId: AgentId;
  amountUsd: number;
  tranche: Tranche;
  reason: string;
  sepoliaTxHash?: Hex;
}

export interface PrioritySettlement {
  collateralId: string;
  seniorFinancier: AgentId;
  seniorAmountUsd: number;
  juniorFinancier: AgentId;
  juniorAmountUsd: number;
  subordinateFinancier?: AgentId;
  subordinateAmountUsd?: number;
  refundedFinanciers: RefundRecord[];
  /** Ordering as proven, in the order the gate enforced it. */
  provenOrder: { agentId: AgentId; blockNumber: number; txIndex: number; seq: number }[];
  settlementBlock: number;
  creditcoinTxHash: Hex;
  settledAt: ISO;
}

// ───────────────────────────── Servicing ─────────────────────────────

export interface DrawRecord {
  collateralId: string;
  obligor: string;
  amountUsd: number;
  maxDrawUsd: number;
  sepoliaTxHash: Hex;
  blockNumber: number;
  drawnAt: ISO;
}

export interface RepaymentRecord {
  collateralId: string;
  obligor: string;
  principalUsd: number;
  interestUsd: number;
  totalUsd: number;
  sepoliaTxHash: Hex;
  blockNumber: number;
  /** Amount decoded from the VERIFIED transaction — not an oracle assertion. */
  provenAmountUsd?: number;
  proofPipelineStatus: ProofPipelineStatus;
  creditcoinTxHash?: Hex;
  repaidAt: ISO;
}

export interface RefinanceRecord {
  collateralId: string;
  oldFinancier: AgentId;
  oldRatePct: number;
  newFinancier: AgentId;
  newRatePct: number;
  amountUsd: number;
  annualSavingsUsd: number;
  oldRepaymentProofHash: Hex;
  newLockProofHash: Hex;
  /** Both liens move in this one transaction — no gap, no double-pledge window. */
  creditcoinTxHash: Hex;
  atomic: true;
  settledAt: ISO;
}

// ───────────────────────────── Failure branch ─────────────────────────────

/**
 * Every failure-branch transition is a PERMISSIONLESS, timestamp-gated keeper poke.
 * No agent needs to be alive for lenders to be protected — the unwind is a property of the
 * contract, not of our uptime.
 */
export interface KeeperPoke {
  fn: string;
  keeper: Hex;
  bountyUsd: number;
  gatedOn: string;
  pokedAtBlock: number;
  creditcoinTxHash?: Hex;
  at: ISO;
}

export interface FreezeRecord {
  collateralId: string;
  reason: "OVERDRAW_ATTEMPT" | "TITLE_DISPUTE" | "PCR_BREACH" | "BREACH_PROVEN";
  detail: string;
  frozenDrawUsd: number;
  poke: KeeperPoke;
}

export interface PcrRecord {
  collateralId: string;
  /** Principal Coverage Ratio: haircut-adjusted collateral value / outstanding principal. */
  pcrPct: number;
  thresholdPct: number;
  shortfallUsd: number;
  topUpRequestedUsd: number;
  topUpPostedUsd: number;
  windowExpiresAt: ISO;
  cured: boolean;
  poke: KeeperPoke;
}

export interface GracePeriodRecord {
  collateralId: string;
  cureAmountUsd: number;
  curedUsd: number;
  cured: boolean;
  openedAt: ISO;
  expiresAt: ISO;
  durationDays: number;
  poke: KeeperPoke;
}

export interface LiquidationRecord {
  collateralId: string;
  /** Descending-price auction of the collateral NFT. */
  startPriceUsd: number;
  floorPriceUsd: number;
  decayBpsPerBlock: number;
  clearingPriceUsd?: number;
  winner?: AgentId;
  proceedsUsd?: number;
  startedAt: ISO;
  clearedAt?: ISO;
  poke: KeeperPoke;
}

export interface DefaultRecord {
  collateralId: string;
  obligor: string;
  proceedsUsd: number;
  /** Strict waterfall: subordinate then junior absorb first loss; senior gets residual. */
  seniorRecoveredUsd: number;
  seniorLossUsd: number;
  juniorLossUsd: number;
  subordinateLossUsd: number;
  /** Permanent, cross-round, recorded on Creditcoin. */
  obligorCreditFlag: "DEFAULT";
  poke: KeeperPoke;
}

export interface BreachRecord {
  collateralId: string;
  detail: string;
  provenBy: AgentId;
  legalEscalation: boolean;
  claimsFrozen: number;
  poke: KeeperPoke;
}

// ───────────────────────────── Waterfall ─────────────────────────────

export interface WaterfallLine {
  agentId: AgentId;
  tranche: Tranche;
  priorityRank: number;
  contributedUsd: number;
  interestDueUsd: number;
  interestEarnedUsd: number;
  principalReturnedUsd: number;
  lossAbsorbedUsd: number;
  payoutUsd: number;
  /** True when this tranche was paid in full before anything flowed to the next. */
  satisfiedInFull: boolean;
}

export interface WaterfallResult {
  realizedRepaymentUsd: number;
  protocolFeeUsd: number;
  proverFeeUsd: number;
  distributableUsd: number;
  /** "REPAYMENT" = performing payoff. "LIQUIDATION" = distressed recovery. */
  kind: "REPAYMENT" | "LIQUIDATION";
  lines: WaterfallLine[];
  unallocatedUsd: number;
  computedAt: ISO;
}

// ───────────────────────────── Prover Calls ─────────────────────────────

export interface ProverCallRecord {
  id: string;
  phase: LifecyclePhase;
  command: string;
  kind: "query" | "proof" | "verify" | "settle" | "keeper";
  summary: string;
  detail: Record<string, string | number>;
  ok: boolean;
  durationMs: number;
  at: ISO;
}

// ───────────────────────────── Attestations ─────────────────────────────

export type AttestationStatus = "pending" | "submitted" | "confirmed" | "failed";

export interface Attestation {
  raceId: RaceId;
  collateralId: string;
  proverId: AgentId;
  claimTokenId: string;
  sepoliaTxHash: Hex;
  creditcoinTxHash?: Hex;
  sourceBlockNumber: number;
  sourceTxIndex: number;
  score: number;
  status: AttestationStatus;
  explorerUrl?: string;
  sourceExplorerUrl?: string;
  attestedAt: ISO;
  error?: string;
}

// ───────────────────────────── Lifecycle ─────────────────────────────

/**
 * The PRECEDENCE protocol state machine.
 *
 * Three tracks share one union:
 *  - PERFORMING: registration → race → proven settlement → draw → servicing → release → closed
 *  - DISTRESSED: the deterministic unwind, every step a permissionless keeper poke
 *  - utility:    AUTO_REFUND (outpaced capital returned) and ABORTED
 */
export const PROTOCOL_STATES = [
  // ── performing track ──
  "COLLATERAL_REGISTERED", // hash-unique NFT minted; clear title verified
  "RACE_OPEN", // financing window open on Sepolia PriorityVault
  "PRIORITY_SETTLED", // 0x0FD2 verified the locks; priority settled by (height, txIndex)
  "CAPITAL_DRAWN", // obligor drew capital from the vault
  "ENCUMBERED", // facility active; lien registered on Creditcoin
  "REFI_DISCOVERED", // Priority Agent proposed a rate improvement
  "ATOMIC_REFINANCE", // one block: old lien released + new lien created
  "REPAYMENT_PROOF", // repayment on Sepolia proven via Attestcoin
  "LIEN_RELEASED", // strict seniority waterfall paid; claims burned
  "SETTLED_CLOSED", // terminal: facility fully resolved, collateral clear

  // ── distressed track (permissionless, timestamp-gated) ──
  "FROZEN_DRAW", // overdraw attempt or title dispute; draws frozen
  "PCR_STABILIZATION", // coverage below threshold; top-up window open
  "GRACE_PERIOD", // repayment overdue; cure window before liquidation
  "DUTCH_LIQUIDATION", // descending-price auction of the collateral NFT
  "TERMINATED_DEFAULT", // terminal: loss allocated, obligor flagged DEFAULT
  "BREACHED", // collateral moved illegally; claims frozen, legal escalation

  // ── utility ──
  "AUTO_REFUND", // race produced locks but allocated nothing; capital returned
  "ABORTED", // terminal: race never became a facility
] as const;

export type LifecyclePhase = (typeof PROTOCOL_STATES)[number];

/** Back-compat alias — prefer PROTOCOL_STATES. */
export const LIFECYCLE_PHASES = PROTOCOL_STATES;

export type RaceTrack = "PERFORMING" | "DISTRESSED";

/**
 * Which storyline this race follows. Set at creation so the demo can trigger the failure act on
 * command rather than waiting for a real default.
 */
export type RaceScenario = "performing" | "default" | "breach";

export type EventLevel = "info" | "success" | "warn" | "error";

export interface LifecycleEvent {
  id: string;
  raceId: RaceId;
  phase: LifecyclePhase;
  level: EventLevel;
  message: string;
  data?: unknown;
  at: ISO;
  seq: number;
}

/**
 * Where a live race actually exists on chain.
 *
 * @remarks Every field here was read back from an RPC — a receipt fetched by hash, or the vault's
 * own storage — never taken from the caller that submitted it. See `sepolia-reader.ts` for why
 * that distinction is the whole of the security model rather than a nicety.
 *
 * Its presence is also what the UI keys explorer links off. A race either has this, in which case
 * its hashes open on a block explorer, or it does not, in which case it is a scripted walkthrough
 * and its hashes are labelled as samples and are deliberately not clickable.
 */
export interface RaceOnChain {
  chainId: number;
  /** The vault that emitted these events. Must equal `collateral.vaultAddress`. */
  vaultAddress: Hex;
  /** The `bytes32` document hash, which is the vault's own key for the facility. */
  collateralId: Hex;
  /** The obligor of record ON THE VAULT, not a stored profile. */
  obligor: Hex;
  registerTxHash?: Hex;
  /**
   * The `openRace` transaction, when this app saw it.
   *
   * @remarks Optional because a race can be recovered from the vault after the fact — a lender
   * bidding into a window opened from another browser or from the CLI. In that case no opening
   * receipt was ever handed to us, and inventing one by reusing the lock's hash would mislabel a
   * real transaction as something it is not. One fewer link is correct; a wrong link is not.
   */
  openTxHash?: Hex;
  /** The block the race was opened in, or the earliest block this app can attribute to it. */
  openBlockNumber: number;
  raceNonce: number;
  /** Unix seconds. The window closes here whatever the app believes. */
  raceDeadline: number;
  facilitySizeUsd: number;
  /** Carried over from the collateral so one page can show both chains' receipts. */
  creditcoinRegisterTx?: Hex;
  creditcoinTermsTx?: Hex;
}

export interface PriorityRace {
  id: RaceId;
  /**
   * True for a scripted walkthrough.
   *
   * @remarks Set at creation, because the orchestrator always runs on simulated adapters — a real
   * settlement needs a proven Sepolia lock and minutes of attestation, so it cannot be what a
   * button produces. Everything hanging off a simulated race is fabricated, including its
   * transaction hashes, which is why the UI must not offer them as explorer links.
   */
  simulated?: boolean;
  /**
   * Chain provenance, present exactly when `simulated` is false.
   *
   * @remarks The two are set together and never independently: a race is live *because* its
   * opening transaction was verified on chain, so there is no state in which one is true and the
   * other missing. Components should test this rather than negating `simulated`, since it also
   * carries the hashes they need.
   */
  onchain?: RaceOnChain;
  status: LifecyclePhase;
  track: RaceTrack;
  scenario: RaceScenario;
  /** The obligor opens the race. Competing financiers have no initiator. */
  obligor: string;
  collateral: CollateralAsset;
  analysis?: CollateralAnalysis;
  extraction?: DocumentExtraction;
  requestedTotalUsd: number;
  decisions: AgentDecision[];
  bids: FinancierBid[];
  locks: SourceLockRecord[];
  proverCalls?: ProverCallRecord[];
  proofRecord?: AttestcoinProofRecord;
  settlement?: PrioritySettlement;
  claims?: PriorityClaim[];
  draw?: DrawRecord;
  refinanceOpportunity?: RefinanceOpportunity;
  refinance?: RefinanceRecord;
  repayment?: RepaymentRecord;
  waterfall?: WaterfallResult;
  attestation?: Attestation;

  // failure branch
  freeze?: FreezeRecord;
  pcr?: PcrRecord;
  gracePeriod?: GracePeriodRecord;
  liquidation?: LiquidationRecord;
  defaulted?: DefaultRecord;
  breach?: BreachRecord;

  aborted?: { reason: string; at: ISO };
  createdAt: ISO;
  updatedAt: ISO;
}

export type RaceOutcome = "won" | "lost" | "rejected" | "defaulted" | "in-progress";

export interface RaceSummary {
  id: RaceId;
  status: LifecyclePhase;
  track: RaceTrack;
  collateralSymbol: string;
  obligor: string;
  bidCount: number;
  totalCapitalUsd: number;
  targetRatePct: number;
  seniorFinancier?: AgentId;
  outcome: RaceOutcome;
  createdAt: ISO;
  updatedAt: ISO;
}

// ───────────────────────────── Aliases ─────────────────────────────

export type Opportunity = CollateralAsset;
export type PoolAnalysis = CollateralAnalysis;
export type SkillCallRecord = ProverCallRecord;
export type SplitResult = WaterfallResult;
export type SplitLine = WaterfallLine;
export type TopPosition = RefinanceOpportunity;
