/**
 * Generate the role keypairs PRECEDENCE needs and write them to ../.env.local (mode 600).
 *
 * Design intent:
 *  - The funded MetaMask key stays the FUNDER and the deployer on both chains. It is the only key
 *    that ever needs a balance you care about.
 *  - Every role gets a FRESH throwaway key. That matters for two roles in particular:
 *      PROVER_CC3  — the prover must be able to be anyone. If it were the deployer, "permissionless
 *                    truth delivery" would be an assertion rather than something a judge can check.
 *      KEEPER_CC3  — the failure branch is meant to be pokeable by an address holding no
 *                    privileges. Same reasoning, and it is the stronger claim of the two.
 *
 * Private keys are written to the env file only. Nothing prints them to stdout — this runs in a
 * terminal whose scrollback outlives the process.
 *
 *   bun run ops/gen-keys.ts            # writes any missing keys, never overwrites an existing one
 *   bun run ops/gen-keys.ts --force    # regenerate everything (invalidates prior funding)
 */
import { ethers } from "ethers";
import { chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ENV_PATH = resolve(import.meta.dir, "../.env.local");
const METAMASK_PATH = resolve(import.meta.dir, "../precedence/.env.metamask");
const force = process.argv.includes("--force");

/** Role → what it does. Order is the order they appear in the env file. */
const ROLES: { key: string; chain: "sepolia" | "cc3"; why: string }[] = [
  { key: "OBLIGOR_PK", chain: "sepolia", why: "Atlas Coffee — draws and repays" },
  { key: "FIN_MERIDIAN_PK", chain: "sepolia", why: "senior-mandate financier" },
  { key: "FIN_VECTOR_PK", chain: "sepolia", why: "balanced financier, takes junior for yield" },
  { key: "FIN_NOVUM_PK", chain: "sepolia", why: "unproven financier, competes for senior" },
  { key: "FIN_REFINANCER_PK", chain: "sepolia", why: "provides replacement capital in the refi beat" },
  { key: "PROVER_CC3_PK", chain: "cc3", why: "permissionless prover — deliberately NOT the deployer" },
  { key: "KEEPER_CC3_PK", chain: "cc3", why: "pokes the failure branch holding zero privileges" },
];

function parseEnv(text: string): Map<string, string> {
  const m = new Map<string, string>();
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i > 0) m.set(t.slice(0, i).trim(), t.slice(i + 1).trim());
  }
  return m;
}

// ── the funder / deployer ──
if (!existsSync(METAMASK_PATH)) {
  console.error(`Funder key not found at ${METAMASK_PATH}`);
  process.exit(1);
}
const funderPk = parseEnv(readFileSync(METAMASK_PATH, "utf8")).get("private_key");
if (!funderPk) {
  console.error("No private_key= line in .env.metamask");
  process.exit(1);
}
const funder = new ethers.Wallet(funderPk.startsWith("0x") ? funderPk : `0x${funderPk}`);

const existing = existsSync(ENV_PATH) ? parseEnv(readFileSync(ENV_PATH, "utf8")) : new Map<string, string>();

const generated: { key: string; address: string; chain: string; why: string; fresh: boolean }[] = [];
const out = new Map(existing);

out.set("FUNDER_PK", funder.privateKey);
out.set("DEPLOYER_SEPOLIA_PK", funder.privateKey);
out.set("DEPLOYER_CC3_PK", funder.privateKey);

for (const r of ROLES) {
  const have = existing.get(r.key);
  if (have && !force) {
    generated.push({ ...r, address: new ethers.Wallet(have).address, fresh: false });
    continue;
  }
  const w = ethers.Wallet.createRandom();
  out.set(r.key, w.privateKey);
  generated.push({ ...r, address: w.address, fresh: true });
}

// ── write the env file, preserving anything already in it ──
const header = `# PRECEDENCE — local secrets. GITIGNORED. Never commit, never paste into a chat.
# Generated by ops/gen-keys.ts on ${new Date().toISOString()}
#
# FUNDER / DEPLOYER (both chains) is the MetaMask account from precedence/.env.metamask.
# Every role below is a fresh throwaway. PROVER_CC3 and KEEPER_CC3 are deliberately NOT the
# deployer, so "permissionless" is checkable rather than claimed.
`;

const lines: string[] = [header];
lines.push("# ── funder / deployer ──");
for (const k of ["FUNDER_PK", "DEPLOYER_SEPOLIA_PK", "DEPLOYER_CC3_PK"]) {
  lines.push(`${k}=${out.get(k)}`);
}
lines.push("");
lines.push("# ── Sepolia roles ──");
for (const r of ROLES.filter((r) => r.chain === "sepolia")) lines.push(`${r.key}=${out.get(r.key)}   # ${r.why}`);
lines.push("");
lines.push("# ── Creditcoin CC3 roles ──");
for (const r of ROLES.filter((r) => r.chain === "cc3")) lines.push(`${r.key}=${out.get(r.key)}   # ${r.why}`);
lines.push("");

// Carry forward everything else already present (RPCs, API keys, addresses).
const managed = new Set(["FUNDER_PK", "DEPLOYER_SEPOLIA_PK", "DEPLOYER_CC3_PK", ...ROLES.map((r) => r.key)]);
const rest = [...out.entries()].filter(([k]) => !managed.has(k));
if (rest.length) {
  lines.push("# ── endpoints, keys, deployed addresses ──");
  for (const [k, v] of rest) lines.push(`${k}=${v}`);
  lines.push("");
}

writeFileSync(ENV_PATH, lines.join("\n"), { mode: 0o600 });
chmodSync(ENV_PATH, 0o600);

// ── report ADDRESSES ONLY ──
console.log(`\nWrote ${ENV_PATH} (mode 600)\n`);
console.log(`FUNDER / DEPLOYER (both chains)`);
console.log(`  ${funder.address}   from precedence/.env.metamask\n`);
console.log(`ROLE KEYS`);
for (const g of generated) {
  console.log(
    `  ${g.fresh ? "NEW " : "kept"}  ${g.chain.padEnd(7)}  ${g.address}  ${g.key.replace("_PK", "").padEnd(18)} ${g.why}`,
  );
}
console.log(`\nNo private key was printed. They are in .env.local only.`);
